### ISSUE TITLE
Pair to mac with .NET Meteor?

### ISSUE THREAD

**Issue by czmirek** [JaneySprings/DotNet.Meteor#79] opened 2024-02-20 12:55 UTC
I work on Windows PC which is in the network with a Mac that has iPhone 12 connected to it.

In Visual Studio there is the **Pair to Mac** functionallity that works well. I pair to Mac and iPhone 12 is detected and I can build and deploy to it and debug my app on it.

Is this possible to do with .NET Meteor?

**Comment by JaneySprings** [comment] 2024-02-20 13:20
Hi, @czmirek ! I think it is a duplicate of #62 

Unfortunately, this option is currently unavailable. I continue experimenting in this direction, but right now I only managed to build an application and deploy it to a device connected to the Windows machine. Still, I'll continue my researches. Thank you for your interest in this feature.

**Comment by czmirek** [comment] 2024-02-20 13:38
> Hi, @czmirek ! I think it is a duplicate of #62
> 
> Unfortunately, this option is currently unavailable. I continue experimenting in this direction, but right now I only managed to build an application and deploy it to an iOS device connected to the Windows machine. Still, I'll continue my researches. Thank you for your interest in this feature.

I mean I don't care whether the iPhone is connected to my Windows machine or to the Mac since both of them are physically next to me. So that works for me as well.

**Comment by JaneySprings** [comment] 2024-02-20 13:52
I see. Still, I cannot include the current implementation as-is, because there are some must have feautes (Hot Reload, Debugging, etc.) that I would like to complete before. Thank you for your patience.

**Comment by czmirek** [comment] 2024-02-20 13:55
Okay thanks for the update :)

**Comment by Ghostbird** [comment] 2024-04-17 08:00
Wouldn't this work by using VCode's remote feature?

**Comment by JaneySprings** [comment] 2024-04-17 10:12
I don't try this case. That is all I know: 
For building on Windows:

```
dotnet build -f:net8.0-ios -p:ServerAddress=<Mac hostname or IP> -p:ServerUser=<user name> -p:ServerPassword=<user password>
```
 
 (Maybe it will work on Linux)
 
 As for running: VisualStudio uses a `Microsoft.iOS.Sdk.Windows` component from workloads. It contains many internal tools like `ideviceinstaller.exe` for installing on physical device. Maybe there is an executable for working with remote simulators?

**Comment by JaneySprings** [comment] 2024-11-14 18:30
**Pair to Mac** has been added in the `6.1.0` version. Check for updates in the VSCode extensions tab.

Check the following [instruction](https://github.com/JaneySprings/DotNet.Meteor/wiki/Build-and-debug-iOS-application-on-Windows-with-Pair-to-Mac) to enable pair to mac in your projects. **Please note that only physical devices (not simulators) are currently supported.**

I'd love to hear your feedback!

**Closed by JaneySprings** 2024-11-14 18:30 UTC
Labels: enhancement
